# Generated by Django 4.0.4 on 2022-06-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('entry_date', models.DateField()),
            ],
        ),
    ]
