# Generated by Django 4.0.4 on 2022-06-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='image',
        ),
    ]
