# Generated by Django 4.0.4 on 2022-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_usertable_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userTable',
        ),
    ]
